name: Checks
on: [ push ]
jobs:
  test:
    name: Go ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.14', '1.15', '1.16']
    steps:
      - name: Go ${{ matrix.go }} on ${{ matrix.os }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup
        run: |
          go get -u golang.org/x/lint/golint
          go get -u golang.org/x/tools/cmd/goimports
      - name: Run lint
        run: golint -set_exit_status $(go list ./... | grep -v /vendor/)
      - name: Run vet
        run: go vet ./...
      - name: Run imports
        run: |
          output=$(goimports -l .)
          echo $output >&2;
          if  [[  ${#output} -ge 1 ]] ; then exit 1; else exit 0; fi
      - name: Run tests
        run: go test ./... -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.go == '1.16'}}
        run: bash <(curl -s https://codecov.io/bash)
  check-result:
    name: Check matrix result
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: exit 0



